### ISSUE TITLE
Would it be possible to add phpmyadmin in the config file?

### ISSUE THREAD

**Issue by garethjax** [celsocelante/docker-lamp#2]
I'm a total newbie to Docker and i don't know if the request is silly, but i would like to use as a "closed" environment for development.

Thanks!

**Comment by celsocelante** [comment]
You can add this following block to the docker-compose file:

```
phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 8890:80
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
```
