### ISSUE TITLE
Unable to access phpmyadmin container's 'localhost' mysqli_connect(): (HY000/2002): Cannot assign requested address

### ISSUE THREAD

**Issue by BRAiNCHiLD95** [celsocelante/docker-lamp#4]
After quite a lot of hours of wondering how to go about using LAMP stack on Docker. I finally decided to use your docker-compose. I've also added the phpmyadmin as per another issue here. I've changed some ports to not run into errors.

My docker-compose looks like this -

```
web:
   image: php:7.2-apache
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "80:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
  ports:
    - "3306:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 8888:80
  environment:
    MYSQL_USER: admin
    MYSQL_PASSWORD: test
    MYSQL_DATABASE: database
```
The problem I'm facing is this -

**Warning: mysqli_connect(): (HY000/2002): Cannot assign requested address in /var/www/html/config.php on line 7**

I tried using the container's IP Address using inspect, that didn't work either. I hope you can shed some light on what I might be doing wrong here.

the config.php file looks like this -

```
<?php
    $host='localhost:8888';
    $username="admin";
    $password="";
    $database="database";
    $conn=mysqli_connect($host,$username,$password,$database);
?>
```

PS: I have changed(removed) the password from inside phpmyadmin
