### ISSUE TITLE
.htaccess and Rewrite

### ISSUE THREAD

**Issue by binaondrej** [celsocelante/docker-lamp#7]
Hi,
I need to use RewriteEngine, but I can not goal. I am pretty new in Docker, so sorry if it is stupid question.

I have `docker-compose.yml` only a bit edited:
```
version: '3.8'
services:
  web:
    container_name: c-web
    image: php:7.4-apache
    environment:
      - ALLOW_OVERRIDE=true
    ports:
      - "80:80"
    links:
      - db
    working_dir: /application
    volumes:
      - .:/application
      - ./www:/var/www/html/

  phpmyadmin:
    container_name: c-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - db
    ports:
      - 8081:80
    environment:
      MYSQL_USER: HOUser
      MYSQL_PASSWORD: HOSokol12.
      MYSQL_DATABASE: HO-Sokol

  db:
    container_name: c-mariadb
    image: mariadb
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_USER: HOUser
      MYSQL_PASSWORD: HOSokol12.
      MYSQL_DATABASE: HO-Sokol
    ports:
      - "3306:3306"
```

and I need to use this `.htaccess` in `www` (html root) directory
```
Require all granted

RewriteEngine On

# redirects hello/world to hello/world.html (if hello/world does not exists)
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME}\.html -f
RewriteRule ^(.*)$ $1.html
```

But when `Rewrite*` is present in `.htaccess`, an error appears 😕
![image](https://user-images.githubusercontent.com/26080108/128184159-26c955b6-5a4c-4688-a6c4-457eef5542df.png)

please, can you help me @celsocelante, @Keirodev or someone else?
